### ISSUE TITLE
Provide default service-name configuration through environment variable

### ISSUE THREAD

**Issue by jroper** [akka/akka-management#411]
Just as the Kubernetes API namespace is looked up from a `$NAMESPACE` environment variable if present, we can do the same for the cluster bootstrap service name, by providing a `$SERVICE_NAME` environment variable. When the kubernetes-api method for discovery is being used, this can be supplied to the pod using:

```yaml
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
```

Note though that in documenting this, we need to be clear about when this can and can't be used. It works for the `kubernetes-api` discovery method because that looks up pods by their labels, rather than services. It doesn't work for the the `async-dns` discovery method, since that uses services, whose names don't necessarily have any relation to the pods labels, and indeed usually the service wanted is suffixed with `-internal`.
