### ISSUE TITLE
Use v1 insteadof v1beta1 for CustomResourceDefinition for kubernetes leases

### ISSUE THREAD

**Issue by danischroeter** [akka/akka-management#849]
### Short description
The kubernetes lease integration uses the beta api for CustomResourceDefinition (apiextensions.k8s.io/v1beta1)
This api will be removed in kubernetes 1.22. see https://github.com/kubernetes/kubernetes/issues/82022
Since kubernetes 1.16 already provides apiextensions.k8s.io/v1 it makes sense to upgrade...

### Details
The only thing preventing me to already implement it is there is need for a mandatory schema (see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/). As i just start with leases i don't know the structure yet...
Since the crdt would still be v1 this would probably just be a documentation change...

new crdt:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: leases.akka.io
spec:
  group: akka.io
  versions:
    - name: v1
      served: true
      storage: true
      #schema: todo
  scope: Namespaced
  names:
    plural: leases
    singular: lease
    kind: Lease
    shortNames:
      - le
```

without the schema one gets:
`The CustomResourceDefinition "leases.akka.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required`

**Comment by danischroeter** [comment]
this would be a working version using v1

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: leases.akka.io
spec:
  group: akka.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                owner:
                  type: string
                time:
                  type: integer
  scope: Namespaced
  names:
    plural: leases
    singular: lease
    kind: Lease
    shortNames:
      - le
```

the properties could be validated even stricter but I think this is not necessary...
```
properties:
  owner:
    type: string
    pattern: '^REGEX...$'
  time:
    type: integer
    minimum: 1
    maximum: 9223372036854775807
```

@chbatey wdyt?
